#!/bin/sh
#
# Simple wrapper script to call a dockerised aspcud
# feel free to improve it
#
cudfpath=$1
cudf=`basename $cudfpath`
solutionpath=$2
solution=`basename $solutionpath`
criteria=$3
volume=/tmp/aspcudwrapper.$$

if [ ! -d $volume ]; then
  mkdir -p $volume
fi

cp $cudfpath $volume/$cudf

sudo docker run -v $volume:/mnt/cudf -i rdicosmo/aspcud:v1 aspcud /mnt/cudf/$cudf /mnt/cudf/$solution "$criteria"

cp $volume/$solution $solutionpath

# cleanup

rm -f $volume/$solution $volume/$cudf
rmdir $volume


